### ISSUE TITLE
Variables allocated adjacent to string variables results in corrupted memory.

### ISSUE THREAD

**Issue by supercom32** [uli/dragonbasic#20]
Bug found during manual testing using Dragon Basic commit ID d2ce042366068083a5fe3089873a22221fffbc26

When working with string variables, I was able to observe that any variables allocated after a string variable gets corrupted memory. This can be observed with the following reduced test case:

#title "TestCase"
#include <gba.dbc>

Dim string1$
Dim string2$

start:
	string1$ = "1234567890"
	Log string1$ + Chr$(13) + Chr$(10)
	string2$ = "ABCDEFGHIJ"
	Log string2$ + Chr$(13) + Chr$(10)
	Log string1$ + Chr$(13) + Chr$(10)
	while
	loop

In this example, you can see that "string1$" gets assigned the value "1234567890". This result is immediately logged to the debug console, with the appropriate ascii codes to skip to the next line. This works just fine. Right after, "string2$" is assigned "ABCDEFGHIJ". This result is also immediately logged, and appears to work just fine. However, if you attempt to read back "string1$" you will now find that it is corrupted. Instead of printing "1234567890" you get this:

`123\nABCDEF`

Where "\n" is used to represent a new line character (at least how it looks like when printed out in VBA debug) . 

In this example the bug causes the first String instance to get corrupted. If instead, you follow up with an Integer instead of a second String, you will notice that the Integer value also gets corrupted. Something about the boundaries between variables isn't being respected. I first noted this problem when I was appending to a String variable like this:

myString$ = myString$ + " Something else"

And then realising that a counter variable that I previously set, which should read "5", is now something ridiculous like "159328413". 

Attached to this issue is a copy of the test case in question. There might be other strange edge cases with string/string manipulation as well you might want to investigate. This seems like a pretty serious issue. 

[Testcase.zip](https://github.com/uli/dragonbasic/files/1648604/Testcase.zip)

**Comment by uli** [comment]
OK, so that's a bad one.

I have reviewed s-alloc, and that seems to be OK. I fail, however, to understand any of the Forth stuff in strings.f (which is unmodified from legacy DB). I suspect there is a problem with append$ (or any of the functions it uses), but I'm not likely to find the time to look into this in detail any time soon...

**Comment by uli** [comment]
Wasn't that magical after all...
