### ISSUE TITLE
Memory corruption occurs even when Strings allocate a maximum size of 64 words (256 bytes)

### ISSUE THREAD

**Issue by supercom32** [uli/dragonbasic#24]
Bug found using Dragon Basic (commit ID: d2ce042366068083a5fe3089873a22221fffbc26) with memory corruption fix applied (commit ID: 901c0e5e88963df44aff28d3124ca842234dad3c)

After applying the original String memory corruption fix, I was still able to observe some edge cases where memory gets corrupted with strings. Because of the complexity of the project I am working on, I'm not sure If I'm able to exactly reproduce the same issue using a reduced test case, but I was able to still at least demonstrate some kind of memory issue with one. For example:

#title "TestCase"
#include <gba.dbc>

#Constant arraySize 100
#Constant initValue (-1)
Dim integer(arraySize)
Dim string$

Sub initializeArray
	Local currentIndex
	Log " "
	For currentIndex = 0 To arraySize
		integer[currentIndex] = initValue
	Next
End Sub

Sub verifyArray
	Local currentIndex
	Log "Verifying array..." + Chr$(13) + Chr$(10)
	For currentIndex = 0 To arraySize
		If Not integer[currentIndex] = initValue
			Log "Memory Corrupted: " + Str$(integer[currentIndex]) + " (Index: " + Str$(currentIndex) + ")" + Chr$(13) + Chr$(10)
		End If
	Next
	Log "Verification complete!" + Chr$(13) + Chr$(10)
End Sub

Sub runTest
	Log " " ;	
	initializeArray
	verifyArray
	string$ = "SOME STRING TO CORRUPT MEMORY"
	verifyArray
End Sub

start:
	runTest
	while
	loop

In this test we simply initalize an array of integers to an obvious number (-1) and then we check the array to make sure every element returns the same value. Then we initialize our string with some value and check the array again. While the first check passes just fine, the second check (after a string is set to a value) fails. The last index appears to have changed. The following is an example of the result in VBA:

Verifying array...
Verification complete!
Verifying array...
Memory Corrupted: 1297044253 (Index: 100)
Verification complete!

As you can see, something has corrupted our last index. In my personal project I am trying to develop, I noted that this corruption happens earlier in my array, but that could be due to it being so complex (across multiple DBC files, arrays, strings, etc - We're talking a whole DBC framework library + game on top of it).

Attached to this issue is the original test case files
[Testcase.zip](https://github.com/uli/dragonbasic/files/1670764/Testcase.zip)

EDIT: It should be noted that I added empty log statements to avoid `!currently_naked' failed.' errors. The fixes that try to address that bug causes other issues with arrays (specifically, comparing string arrays produce ' unknown word compare' errors), so I did not apply those fixes to my build of Dragon Basic.

**Comment by supercom32** [comment]
Progress Update:  I'm still trying to find better test cases that can demonstrate memory corruption (in whatever way possible) .

I've tried using VBA to view my WRAM in realtime and it appears that arrays of Strings might be one edge case which can still cause memory corruption. Specifically, if you dimension a string array, and then dimension an Integer array, they seem to overlap the same area of memory. Ie. If you set the Integer array to some default value (65535 for example) and then set some value in your string array, you'll see in WRAM a field of "FF"'s which is correct, with garbage mixed in periodically (at least in my project). Maybe there is some "free" memory calculation which isn't properly taking into account that Strings are now 64 words long (Shrugs)?

Anyway, hopefully I can find a simple reproducible test case for this. When find one, I'll attach it to this issue. In the meantime I'll keep investigating!

**Comment by supercom32** [comment]
Update: Horay! I was finally able to nail down the bug!

The memory corruption issue is with importing "*.DBC" modules! If you have one module which dimensions an array, and a separate module that also dimensions an array, they both seem to get allocated the same area in memory (as if they don't know memory has already been reserved by the other)! If you do this all in a single DBC module, it doesn't have this problem and you won't see the issue. Observe the following code:

MAIN.DBC
--------------
#title "TestCase"
#include <gba.dbc>
#include "./stringArray.dbc"

#Constant CONST_INTEGER_ARRAY_SIZE 200
Dim myIntegerArray(CONST_INTEGER_ARRAY_SIZE)

Sub initializeIntegerArray
	Local currentIndex
	Log " "
	For currentIndex = 0 To CONST_INTEGER_ARRAY_SIZE
		myIntegerArray[currentIndex] = 65535
	Next
End Sub

Start:
	initializeIntegerArray
	initializeStringArray
	While
	Loop

STRINGARRAY.DBC
---------------------------
#Constant CONST_STRING_ARRAY_SIZE 20
Dim myStringArray$(CONST_STRING_ARRAY_SIZE)
Sub initializeStringArray
	Local currentIndex
	Log " "
	For currentIndex = 0 To CONST_STRING_ARRAY_SIZE
		myStringArray$[currentIndex] = "ABCDEF"
	Next
End Sub

In this test, you can see that the "main.dbc" module creates an integer array and contains a method to initialize all the elements to 65535 (FFFF). In the "stringArray.dbc" module, it has a string array and a method to initialize all it's elements to "ABCDEF".

Now, when the program starts, it will initialize the Integer array in memory, then externally call the "stringArray.dbc" module to initialize the string array. Now if you look at VBA and then launch the "Memory Viewer" under the menu "Tools", select from the drop down menu "0x02000000 - WRAM".

Notice what you see!

![alt text](https://user-images.githubusercontent.com/27777553/35707308-20f8db5a-07a1-11e8-8bfa-f0f3c5865f3f.png) 

You get a field of "FFFF" values (which is correct) but you also get "ABCDEF" peppered all over the same memory location! I don't know if this happens with non-arrays (It's not as easy to tell with shorter memory allocations), but it should be verified as well just to be sure.

Hopefully this can be fixed as it basically makes importing "*.DBC" libraries quite dangerous to program stability! 

As always, here is the files for easy use: [ArrayTestCase.zip](https://github.com/uli/dragonbasic/files/1687517/ArrayTestCase.zip)

**Comment by uli** [comment]
The bit with the modules is a red herring. The reason that this code triggered the bug is that here the string array is allocated first. The code in DBC responsible for that did not take the string size increase into account, so it did not allocate enough memory.

I have inspected the generated code, and it looks fine now. I have not actually tested the fix because I don't have a suitable emulator at hand right now. Sorry this took so long.
