### ISSUE TITLE
The interrupt function 'onVCount' does not accept two parameters as described in the documentation.

### ISSUE THREAD

**Issue by supercom32** [uli/dragonbasic#3]
Issue found using the latest version of Dragon Basic under Linux (Commit ID : d2ce042366068083a5fe3089873a22221fffbc26).

The interrupt function 'onVCount' should accept two parameters; The interrupt to fire and the scan line to fire the interrupt on. The documentation confirms this, but the actual 'interrupts.dbc' file only specifies one parameter (the interrupt to fire). The user can't select which scanline to fire on.

**Comment by uli** [comment]
Looks like it's simply a matter of a wrong prototype. Should be fixed now, but hasn't been tested as I'm running out of time. See you again in another five years! ;)

**Comment by supercom32** [comment]
Hi Uli,

I'm truly impressed by your dedication and hard work! I'm not sure if I have my development environment anymore (Since I wasn't sure if any of these stability issues would ever get addressed), but I guess I just need to check back in 5 year increments to see. :smile: 

I want to emphasize how unique and irreplaceable your project is—I've scoured for alternatives without success. Unfortunately, it's complex enough that I lack the expertise in Assembly, compilers, or low-level programming to fix issues myself. I figured the best I could do is encourage continued fixes by reporting issues as completely and thoroughly as possible to make your job easier. 

I'm not certain if there have been enough fixes to make Dragon Basic development reliable enough for a serious game/project (given all the stability errors and bugs I reported). However, I'd be willing to dive back in and assess the current state of affairs. Do you happen to have an archive of DevKitPro or a list of compatible Linux distro versions you used for these fixes? I'm concerned that tracking down the exact version of DevKitPro compatible with DBC, or potentially other libraries, might prove challenging. Finding older distros is probably the easiest part. If i can find my VirtualBox image I used for this, it might make things trivial to get back in the game.

See you in 5 more years!

Alex,

**Comment by uli** [comment]
Somewhat surprisingly, the current version of devkitPro as installed using the method described in https://devkitpro.org/wiki/devkitPro_pacman worked just fine for me.
