### ISSUE TITLE
Checking the condition of a string to be empty causes MF to generate a segmentation fault.

### ISSUE THREAD

**Issue by supercom32** [uli/dragonbasic#4]
Issue found using the latest version of Dragon Basic under Linux (Commit ID: d2ce042366068083a5fe3089873a22221fffbc26)

Checking the condition of a string to be empty (Ie. "") causes MF to generate a segmentation fault. This is sometimes useful when you want to mark a String as NULL, empty, or uninitialised and you check it by seeing if it's empty or not. Since MF crashes when doing so, the users only recourse is to set a string to some unique identifier that means the same thing (Ie. "-1", "NULL", etc) and hope they never need a real string of that value.

**Comment by uli** [comment]
This should be fixed by the same commit that fixed issue #5.

**Comment by uli** [comment]
closing
