### ISSUE TITLE
Strings cannot be instantiated as local variables (Type mis-match?).

### ISSUE THREAD

**Issue by supercom32** [uli/dragonbasic#6]
Issue found using the latest version of Dragon Basic under Linux (Commit ID: d2ce042366068083a5fe3089873a22221fffbc26)

Strings cannot be instantiated as local variables. Instead the user is given a "Type mis-match?" error. Not allowing local Strings may be design intent, but the documentation doesn't seem to mention anything about this limitation. As far as I know, documentation just mentions that local variables are faster and more efficient, so use it as much as you can.

**Comment by uli** [comment]
That is correct on both counts: it is both intentional and undocumented (except for a mention in the commit log).

The limitation is now documented. Have a nice day. :)
